ALTER TABLE services ADD COLUMN IF NOT EXISTS faqs JSONB NOT NULL DEFAULT '[]';
ALTER TABLE services ADD COLUMN IF NOT EXISTS seo_title TEXT NOT NULL DEFAULT '';
ALTER TABLE services ADD COLUMN IF NOT EXISTS seo_description TEXT NOT NULL DEFAULT '';
